package org.gnucash.apiext.trxmgr;

import org.gnucash.api.read.GnuCashTransactionSplit;
import org.gnucash.api.write.GnuCashWritableFile;
import org.gnucash.api.write.GnuCashWritableTransaction;
import org.gnucash.api.write.GnuCashWritableTransactionSplit;
import org.gnucash.api.write.impl.GnuCashWritableTransactionSplitImpl;
import org.gnucash.base.basetypes.simple.GCshSpltID;
import org.gnucash.base.basetypes.simple.GCshTrxID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TransactionMergerVar2 extends TransactionMergerBase
								   implements IFTransactionMerger 
{
    // Logger
    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionMergerVar2.class);
    
    // ---------------------------------------------------------------
    
	// CAUTION: 
	// In this merger variant, the survivor trx's bank split will be deleted
	// and vice versa.
	// ==> The zdTrxBankSpltID (ZD Splt), part of the dier trx, will die, 
	//     but a copy of it will survive as part of the survivor trx, 
	//     called ZS Splt/after.
        //
	// Visualization of Typical Example:
	// ---------------------------------
	//
	// Dier Trx                            Survivor Trx
        // (imported from bank)                (generated by JKMyMoneyLib)
	// |                                   +-- XS Splt (to stock account)
	// |                                   +-- YS.a Splt (to expenses account)
	// |                                   +-- YS.b Splt (to expenses account)
	// |                                   +-- YS.c Splt (to income account)
	// +-- ZD Splt (to bank acct)          +-- ZS Splt/before (to bank account)
	//     ^                               |   ^
	//     +-- will be copied to           |   +-- Will be replaced by ZS Splt/after
	//         survivor trx -------------> +-- ZS Splt/after (to bank account)
	//                                         ^
	//                                         +-- Copy of ZD Splt
        //
	// Notice the the dier trx is not sane/balanced; it consists of one
        // single split. However, it might be marked as reconciled.
	// 
	// Let that sink in for a moment before you review the code in this class.

	private GnuCashWritableTransaction survTrx = null;
	private GnuCashWritableTransaction dierTrx = null;
	
	private GnuCashTransactionSplit zDierTrxBankSplt = null; // "ZS Split/before"
	private GnuCashTransactionSplit zSurvTrxBankSpltBefore = null; // "ZS Split/before"
	
	private GCshSpltID zDierTrxBankSpltID = null;       // cf. above
	private GCshSpltID zSurvTrxBankSpltBeforeID = null; // dto.

	private boolean postDateFromDierTrx = false;

    // ---------------------------------------------------------------
	
	public TransactionMergerVar2(GnuCashWritableFile gcshFile) {
		super(gcshFile);
		setVar(Var.VAR_2);
	}
    
    // ---------------------------------------------------------------
	
	public GCshSpltID getZDierTrxBankSpltID() {
		return zDierTrxBankSpltID;
	}
    
	public void setZDierTrxBankSpltID(GCshSpltID spltID) {
		this.zDierTrxBankSpltID = spltID;
		
		zDierTrxBankSplt = gcshFile.getTransactionSplitByID(spltID);
	}
	
	// ---
    
	public GCshSpltID getZSurvTrxBankSpltBeforeID() {
		return zSurvTrxBankSpltBeforeID;
	}
    
	public void setZSurvTrxBankSpltBeforeID(GCshSpltID spltID) {
		this.zSurvTrxBankSpltBeforeID = spltID;
		
		zSurvTrxBankSpltBefore = gcshFile.getTransactionSplitByID(spltID);
	}
    
	// ---
    
	public GnuCashWritableTransaction getSurvTrx() {
		return survTrx;
	}
    
	public void setSurvTrx(GnuCashWritableTransaction trx) {
		this.survTrx = trx;
	}
    
	public GnuCashWritableTransaction getDierTrx() {
		return dierTrx;
	}
    
	public void setDierTrx(GnuCashWritableTransaction trx) {
		this.dierTrx = trx;
	}
    
	// ---
	
	public boolean isPostDateFromDierTrxSet() {
		return postDateFromDierTrx;
	}
    
	public void setPostDateFromDierTrx(boolean val) {
		postDateFromDierTrx = val;
	}
    
    // ---------------------------------------------------------------
    
	@Override
	public void merge(GCshTrxID survivorID, GCshTrxID dierID) throws MergePlausiCheckException {
		GnuCashWritableTransaction survivor = gcshFile.getWritableTransactionByID(survivorID);
		GnuCashWritableTransaction dier = gcshFile.getWritableTransactionByID(dierID);
		merge(survivor, dier);
	}

	@Override
	public void merge(GnuCashWritableTransaction survivor, GnuCashWritableTransaction dier) throws MergePlausiCheckException {
		if ( survivor == null ) {
			throw new IllegalArgumentException("argument <survivor> is null");
		}
		
		if ( ! survivor.getID().isSet() ) {
			throw new IllegalArgumentException("argument <survivor>'s ID is not set");
		}
		
		if ( dier == null ) {
			throw new IllegalArgumentException("argument <dier> is null");
		}
		
		if ( ! dier.getID().isSet() ) {
			throw new IllegalArgumentException("argument <dier>'s ID is not set");
		}
		
		// ---
		
		setSurvTrx(survivor);
		setDierTrx(dier);
		
		// ---
		
		if ( zDierTrxBankSpltID == null ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is null");
		}
		
		if ( zSurvTrxBankSpltBeforeID == null ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is null");
		}
		
		if ( ! zDierTrxBankSpltID.isSet() ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is not set");
		}
		
		if ( ! zSurvTrxBankSpltBeforeID.isSet() ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is not set");
		}
		
		if ( zDierTrxBankSpltID.equals(zSurvTrxBankSpltBeforeID) ) {
			throw new IllegalStateException("IDs of Z dier Trx bank Split and Z survivor Trx bank Split (before) are identical");
		}
		
		// ---
		
		// 1) Perform plausi checks
		if ( plausiCheck(survivor, dier) ) {
			LOGGER.info("merge: survivor-dier-pair passed plausi check: " + survivor.getID() + "/" + dier.getID());
		} else {
			LOGGER.error("merge: survivor-dier-pair did not pass plausi check: " + survivor.getID() + "/" + dier.getID());
			throw new MergePlausiCheckException();
		}

		GnuCashWritableTransactionSplit zSurvBankTrxSpltAfter = copyBankTrxSplt();
		LOGGER.info("merge: Transaction Split " + zDierTrxBankSpltID + " copied to new Splt " + zSurvBankTrxSpltAfter.getID());
		
		GnuCashWritableTransactionSplit zSurvBankTrxSpltBefore = gcshFile.getWritableTransactionSplitByID(zSurvTrxBankSpltBeforeID);
		survTrx.removeSplit(zSurvBankTrxSpltBefore);
		LOGGER.info("merge: Removed Transaction Split " + zSurvTrxBankSpltBeforeID);

		if ( postDateFromDierTrx )
			survTrx.setDatePosted( dierTrx.getDatePosted().toLocalDate() );

		GCshTrxID dierID = dier.getID();
		gcshFile.removeTransaction(dier);
		LOGGER.info("merge: Transaction " + dierID + " (dier) removed");
	}

    // ---------------------------------------------------------------
	
	private GnuCashWritableTransactionSplit copyBankTrxSplt() {
		GnuCashWritableTransactionSplit copy = survTrx.createWritableSplit(zDierTrxBankSplt.getAccount());

		if ( zDierTrxBankSplt.getAction() != null )
			copy.setAction(zDierTrxBankSplt.getAction());
		
		copy.setAccountID(zSurvTrxBankSpltBefore.getAccountID());
		
		copy.setValue(zDierTrxBankSplt.getValueRat());
		copy.setQuantity(zDierTrxBankSplt.getQuantityRat());
		
		if ( zDierTrxBankSplt.getReconState() != null )
			copy.setReconState(zDierTrxBankSplt.getReconState());
		
		if ( zDierTrxBankSplt.getDescription() != null )
			copy.setDescription(zDierTrxBankSplt.getDescription());

		if ( zDierTrxBankSplt.getUserDefinedAttributeKeys() != null ) {
			for ( String attrKey : zDierTrxBankSplt.getUserDefinedAttributeKeys() ) {
				if ( copy.getUserDefinedAttributeKeys() != null ) {
					if ( copy.getUserDefinedAttributeKeys().contains(attrKey) ) {
						copy.setUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
					} else {
						copy.addUserDefinedAttribute( ((GnuCashWritableTransactionSplitImpl) zDierTrxBankSplt).getUserDefinedAttributeType(attrKey), 
													  attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
					}
				} else {
					copy.addUserDefinedAttribute( ((GnuCashWritableTransactionSplitImpl) zDierTrxBankSplt).getUserDefinedAttributeType(attrKey),
												  attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
				}
			} // for
		}
		
		return copy;
	}

}
